//! The loopback web surface: an authenticated HTTP API over the existing
//! services, plus the static UI that reads it.
//!
//! Three rules shape this module, and each one is a decision rather than a
//! convenience (see `ADR-N10`):
//!
//! 1. **No route writes SQL.** Every mutation goes through `SessionService`, so
//!    ownership, policy and durability stay with their owners.
//! 2. **Loopback is not an authentication boundary.** Another process on the
//!    same machine can reach a loopback port, so every mutation carries a token
//!    the host generated at startup, and every request carries an `Origin` the
//!    allowlist accepts.
//! 3. **The event cursor is the journal sequence**, not a counter of what this
//!    process happens to have buffered. A cursor older than the retained range
//!    is answered with an explicit `gap`, because a client that silently
//!    receives a partial replay believes it is up to date.

use std::{convert::Infallible, net::SocketAddr, sync::Arc, time::Duration};

use bytes::Bytes;
use http_body_util::{BodyExt, Full, StreamBody, combinators::BoxBody};
use hyper::{
    Method, Request, Response, StatusCode,
    body::{Frame, Incoming},
    header::{self, HeaderValue},
    service::service_fn,
};
use hyper_util::rt::TokioIo;
use serde_json::{Value, json};
use tokio::sync::mpsc;

use harness_session::{AdmitInputRequest, SessionService};
use harness_store_sqlite::SqliteStore;
use harness_types::{
    ContentHash, ErrorCode, HarnessError, HostId, InputId, ProjectId, SessionId, SourceAuthority,
    WorkspaceObservation,
};

pub mod assets;

/// How many events one connection may fall behind before it is cut.
///
/// A subscriber that cannot keep up must not be able to hold host memory: the
/// buffer is the bound, and the cut is reported as a gap rather than as silence.
pub const LIVE_BUFFER_EVENTS: usize = 256;

/// Maximum JSON body accepted by the input mutation route.
pub const MAX_INPUT_BODY_BYTES: usize = 64 * 1024;

/// The token header a mutation must carry.
pub const SESSION_HEADER: &str = "x-ha-session";

/// The request id header that makes a mutation idempotent.
pub const REQUEST_ID_HEADER: &str = "x-ha-request-id";

/// What the server was started with.
#[derive(Clone, Debug)]
pub struct WebConfig {
    pub data_dir: std::path::PathBuf,
    /// Bind address. Defaults to loopback; a non-loopback bind is refused.
    ///
    /// Port `0` asks the operating system for a free port, which is what a test
    /// does; the same-origin allowlist is derived from the address that was
    /// actually bound, not from this request, so an ephemeral port still accepts
    /// its own origin.
    pub bind: SocketAddr,
    /// Token a mutation must present. Generated by the caller, printed once.
    pub session_token: String,
    /// Origins accepted for a mutation, in addition to same-origin loopback.
    pub allowed_origins: Vec<String>,
}

impl WebConfig {
    /// A loopback configuration with a fresh token.
    #[must_use]
    pub fn loopback(data_dir: impl Into<std::path::PathBuf>, port: u16) -> Self {
        Self {
            data_dir: data_dir.into(),
            bind: SocketAddr::from(([127, 0, 0, 1], port)),
            session_token: new_token(),
            allowed_origins: Vec::new(),
        }
    }

    /// Refuse anything that is not a loopback bind.
    ///
    /// The plan forbids binding public by default and this release has no
    /// threat model for it, so a non-loopback address is a typed refusal rather
    /// than a warning.
    pub fn validate(&self) -> Result<(), HarnessError> {
        if !self.bind.ip().is_loopback() {
            return Err(HarnessError::new(
                ErrorCode::PolicyDenied,
                "the web surface binds loopback only; a public bind has no threat model in this release",
            ));
        }
        if self.session_token.trim().len() < 16 {
            return Err(HarnessError::new(
                ErrorCode::InvalidPayload,
                "the web session token needs at least 16 characters of entropy",
            ));
        }
        Ok(())
    }

    /// Whether an `Origin` header is acceptable for a mutation.
    ///
    /// Same-origin loopback is always allowed; anything else has to be listed.
    /// Mutations without an `Origin` fail closed.
    #[must_use]
    pub fn origin_allowed(&self, origin: Option<&str>) -> bool {
        let Some(origin) = origin else { return false };
        if self.allowed_origins.iter().any(|allowed| allowed == origin) {
            return true;
        }
        let port = self.bind.port();
        [
            format!("http://127.0.0.1:{port}"),
            format!("http://localhost:{port}"),
            format!("http://[::1]:{port}"),
        ]
        .iter()
        .any(|allowed| allowed == origin)
    }

    /// Whether the request's authority names this loopback server.
    #[must_use]
    pub fn host_allowed(&self, host: Option<&str>) -> bool {
        let Some(host) = host else { return false };
        let port = self.bind.port();
        [
            format!("127.0.0.1:{port}"),
            format!("localhost:{port}"),
            format!("[::1]:{port}"),
        ]
        .iter()
        .any(|allowed| allowed.eq_ignore_ascii_case(host))
    }
}

/// A 32-character token from the system's own entropy.
fn new_token() -> String {
    // Two v7 UUIDs: 256 bits of the OS entropy source the ID generator already
    // uses, in a form that is safe in a header and readable in a terminal.
    format!(
        "{}{}",
        harness_types::EventId::generate()
            .as_str()
            .trim_start_matches("event_")
            .replace('-', ""),
        harness_types::EventId::generate()
            .as_str()
            .trim_start_matches("event_")
            .replace('-', "")
    )
}

/// The running server, as a test or a caller sees it.
pub struct WebHandle {
    pub address: SocketAddr,
    pub token: String,
}

type Body = BoxBody<Bytes, Infallible>;

fn full(body: impl Into<Bytes>) -> Body {
    Full::new(body.into())
        .map_err(|never| match never {})
        .boxed()
}

fn json_response(status: StatusCode, value: &Value) -> Response<Body> {
    let text = serde_json::to_string(value).unwrap_or_else(|_| "{}".to_owned());
    let mut response = Response::new(full(text));
    *response.status_mut() = status;
    response.headers_mut().insert(
        header::CONTENT_TYPE,
        HeaderValue::from_static("application/json"),
    );
    response
        .headers_mut()
        .insert(header::CACHE_CONTROL, HeaderValue::from_static("no-store"));
    response
}

/// The error envelope CONTRACTS §9 fixes, with the request id when there is one.
fn error_response(
    status: StatusCode,
    code: ErrorCode,
    message: &str,
    request_id: Option<&str>,
) -> Response<Body> {
    json_response(
        status,
        &json!({
            "schema_version": 1,
            "status": "error",
            "request_id": request_id,
            "error": {
                "code": code.as_str(),
                "retry_class": code.retry_class().as_str(),
                "safe_message": message,
            },
        }),
    )
}

fn status_for(code: ErrorCode) -> StatusCode {
    match code {
        ErrorCode::PolicyDenied | ErrorCode::MissingAuthority | ErrorCode::ScopeAuthorityDenied => {
            StatusCode::UNAUTHORIZED
        }
        ErrorCode::IdempotencyConflict | ErrorCode::SequenceConflict => StatusCode::CONFLICT,
        ErrorCode::InvalidPayload | ErrorCode::InvalidSequence | ErrorCode::InvalidId => {
            StatusCode::BAD_REQUEST
        }
        ErrorCode::TaskNotFound => StatusCode::NOT_FOUND,
        _ => StatusCode::INTERNAL_SERVER_ERROR,
    }
}

/// Serve the web surface until the process is cancelled.
///
/// # Errors
/// Fails when the configuration is refused or the listener cannot bind.
pub async fn serve(config: WebConfig) -> Result<WebHandle, HarnessError> {
    config.validate()?;
    let listener = tokio::net::TcpListener::bind(config.bind)
        .await
        .map_err(|error| {
            HarnessError::new(
                ErrorCode::ServiceUnavailable,
                format!("cannot bind {}: {error}", config.bind),
            )
        })?;
    let address = listener.local_addr().map_err(|error| {
        HarnessError::new(
            ErrorCode::ServiceUnavailable,
            format!("cannot read the bound address: {error}"),
        )
    })?;
    // The allowlist follows the port that was actually bound: with port 0 the
    // configured port is a request, and a same-origin mutation would otherwise
    // be refused for naming the real one.
    let mut bound = config;
    bound.bind = address;
    let state = Arc::new(bound);
    let handle = WebHandle {
        address,
        token: state.session_token.clone(),
    };
    tokio::spawn(async move {
        loop {
            let (stream, _peer) = match listener.accept().await {
                Ok(pair) => pair,
                Err(error) => {
                    eprintln!("ha web: accept failed, the surface is stopping: {error}");
                    break;
                }
            };
            let state = Arc::clone(&state);
            tokio::spawn(async move {
                let io = TokioIo::new(stream);
                let service = service_fn(move |request| {
                    let state = Arc::clone(&state);
                    async move { Ok::<_, Infallible>(route(state, request).await) }
                });
                // A connection error is reported rather than swallowed: a
                // response that never arrives looks identical to a hang from
                // the client side, and that is exactly the failure a test
                // cannot diagnose.
                if let Err(error) = hyper::server::conn::http1::Builder::new()
                    .serve_connection(io, service)
                    .await
                {
                    // Reported rather than swallowed: a response that never
                    // arrives looks identical to a hang from the client side.
                    eprintln!("ha web: connection ended: {error}");
                }
            });
        }
    });
    Ok(handle)
}

/// One request, dispatched.
#[allow(clippy::too_many_lines)] // routing, auth and body limits share one request boundary
async fn route(state: Arc<WebConfig>, request: Request<Incoming>) -> Response<Body> {
    let method = request.method().clone();
    let path = request.uri().path().to_owned();
    let query = request.uri().query().unwrap_or_default().to_owned();
    let origin = request
        .headers()
        .get(header::ORIGIN)
        .and_then(|value| value.to_str().ok())
        .map(str::to_owned);
    let host = request
        .headers()
        .get(header::HOST)
        .and_then(|value| value.to_str().ok())
        .map(str::to_owned);
    let token = request
        .headers()
        .get(SESSION_HEADER)
        .and_then(|value| value.to_str().ok())
        .map(str::to_owned);
    let request_id = request
        .headers()
        .get(REQUEST_ID_HEADER)
        .and_then(|value| value.to_str().ok())
        .map(str::to_owned);

    match (method, path.as_str()) {
        (Method::GET, "/api/health") => json_response(
            StatusCode::OK,
            &json!({
                "schema_version": 1,
                "status": "ok",
                "version": env!("CARGO_PKG_VERSION"),
                "live_buffer_events": LIVE_BUFFER_EVENTS,
            }),
        ),
        (Method::GET, "/api/sessions") => list_sessions(&state).await,
        (Method::GET, "/" | "/index.html") => assets::static_response("/index.html"),
        (Method::GET, path) if path.starts_with("/assets/") => assets::static_response(path),
        (Method::GET, path) if path.starts_with("/api/sessions/") => {
            let rest = path.trim_start_matches("/api/sessions/");
            let (session, tail) = match rest.split_once('/') {
                Some((session, tail)) => (session.to_owned(), tail.to_owned()),
                None => (rest.to_owned(), String::new()),
            };
            match tail.as_str() {
                "state" => session_state(&state, &session).await,
                "events" => session_events(&state, &session, &query).await,
                _ => error_response(
                    StatusCode::NOT_FOUND,
                    ErrorCode::TaskNotFound,
                    "no such route",
                    None,
                ),
            }
        }
        (Method::POST, path) if path.starts_with("/api/sessions/") => {
            let rest = path.trim_start_matches("/api/sessions/");
            let Some((session, "inputs")) = rest.split_once('/') else {
                return error_response(
                    StatusCode::NOT_FOUND,
                    ErrorCode::TaskNotFound,
                    "no such route",
                    None,
                );
            };
            // Authentication and origin are checked before the body is read, so
            // an unauthenticated caller cannot make the host allocate for it.
            if let Some(response) = authorize(
                &state,
                token.as_deref(),
                origin.as_deref(),
                host.as_deref(),
                request_id.as_deref(),
            ) {
                return response;
            }
            let body = match read_limited_body(request.into_body()).await {
                Ok(body) => body,
                Err(BodyReadError::TooLarge) => {
                    return error_response(
                        StatusCode::PAYLOAD_TOO_LARGE,
                        ErrorCode::InvalidPayload,
                        "the request body exceeds the 64 KiB limit",
                        request_id.as_deref(),
                    );
                }
                Err(BodyReadError::Read(error)) => {
                    return error_response(
                        StatusCode::BAD_REQUEST,
                        ErrorCode::InvalidPayload,
                        &format!("the request body could not be read: {error}"),
                        request_id.as_deref(),
                    );
                }
            };
            admit_input(&state, session, &body, request_id.as_deref()).await
        }
        _ => error_response(
            StatusCode::NOT_FOUND,
            ErrorCode::TaskNotFound,
            "no such route",
            None,
        ),
    }
}

/// Refuse an unauthenticated or cross-origin mutation.
fn authorize(
    state: &WebConfig,
    token: Option<&str>,
    origin: Option<&str>,
    host: Option<&str>,
    request_id: Option<&str>,
) -> Option<Response<Body>> {
    match token {
        Some(token) if constant_time_eq(token, &state.session_token) => {}
        _ => {
            return Some(error_response(
                StatusCode::UNAUTHORIZED,
                ErrorCode::MissingAuthority,
                "a mutation requires the session token this host printed at startup",
                request_id,
            ));
        }
    }
    if !state.host_allowed(host) || !state.origin_allowed(origin) {
        return Some(error_response(
            StatusCode::FORBIDDEN,
            ErrorCode::PolicyDenied,
            "the request Host and Origin must name this loopback server or an allowed origin",
            request_id,
        ));
    }
    None
}

enum BodyReadError {
    TooLarge,
    Read(hyper::Error),
}

async fn read_limited_body(mut body: Incoming) -> Result<Bytes, BodyReadError> {
    let mut bytes = Vec::new();
    let mut received = 0_usize;
    let mut oversized = false;
    while let Some(frame) = body.frame().await {
        let frame = frame.map_err(BodyReadError::Read)?;
        if let Ok(data) = frame.into_data() {
            received = received.saturating_add(data.len());
            if received > MAX_INPUT_BODY_BYTES {
                oversized = true;
                // Keep memory bounded while draining a rejected body so the
                // server can still return a typed 413 on a reusable connection.
                if received > MAX_INPUT_BODY_BYTES * 16 {
                    return Err(BodyReadError::TooLarge);
                }
            } else {
                bytes.extend_from_slice(&data);
            }
        }
    }
    if oversized {
        Err(BodyReadError::TooLarge)
    } else {
        Ok(Bytes::from(bytes))
    }
}

/// Compare two secrets without leaking their common prefix length.
fn constant_time_eq(left: &str, right: &str) -> bool {
    let (left, right) = (left.as_bytes(), right.as_bytes());
    if left.len() != right.len() {
        return false;
    }
    left.iter()
        .zip(right)
        .fold(0_u8, |acc, (a, b)| acc | (a ^ b))
        == 0
}

async fn open_store(state: &WebConfig) -> Result<SqliteStore, HarnessError> {
    SqliteStore::open_read_only(&state.data_dir)
        .await
        .map_err(|error| HarnessError::new(error.code(), error.to_string()))
}

async fn list_sessions(state: &WebConfig) -> Response<Body> {
    let store = match open_store(state).await {
        Ok(store) => store,
        Err(error) => {
            return error_response(
                status_for(error.code()),
                error.code(),
                error.message(),
                None,
            );
        }
    };
    let sessions = match store.list_sessions().await {
        Ok(sessions) => sessions,
        Err(error) => {
            return error_response(
                StatusCode::INTERNAL_SERVER_ERROR,
                error.code(),
                &error.to_string(),
                None,
            );
        }
    };
    let body = json!({
        "schema_version": 1,
        "status": "ok",
        "sessions": sessions.iter().map(|summary| json!({
            "session_id": summary.session_id,
            "task_id": summary.task_id,
            "next_sequence": summary.next_sequence,
            "input_count": summary.input_count,
        })).collect::<Vec<_>>(),
    });
    let _ = store.close().await;
    json_response(StatusCode::OK, &body)
}

async fn session_state(state: &WebConfig, session: &str) -> Response<Body> {
    let session_id = match SessionId::parse(session) {
        Ok(id) => id,
        Err(error) => {
            return error_response(StatusCode::BAD_REQUEST, error.code(), error.message(), None);
        }
    };
    let store = match open_store(state).await {
        Ok(store) => store,
        Err(error) => {
            return error_response(
                status_for(error.code()),
                error.code(),
                error.message(),
                None,
            );
        }
    };
    let summary = match store.session_summary(&session_id).await {
        Ok(summary) => summary,
        Err(error) => {
            return error_response(
                StatusCode::INTERNAL_SERVER_ERROR,
                error.code(),
                &error.to_string(),
                None,
            );
        }
    };
    let Some(summary) = summary else {
        let _ = store.close().await;
        return error_response(
            StatusCode::NOT_FOUND,
            ErrorCode::TaskNotFound,
            "no such session",
            None,
        );
    };
    // The projection and the newest events: this is the reload path a client
    // takes after a gap, so it has to describe committed state, not a buffer.
    let projection = match store.current_projection(&summary.task_id).await {
        Ok(projection) => projection,
        Err(error) => {
            let _ = store.close().await;
            return error_response(
                StatusCode::INTERNAL_SERVER_ERROR,
                error.code(),
                &error.to_string(),
                None,
            );
        }
    };
    let through = summary.next_sequence.saturating_sub(1);
    let from = through.saturating_sub(31);
    let events = match store.load_events_after_limit(&session_id, from, 32).await {
        Ok(events) => events
            .into_iter()
            .filter(|event| event.seq <= through)
            .collect::<Vec<_>>(),
        Err(error) => {
            let _ = store.close().await;
            return error_response(
                StatusCode::INTERNAL_SERVER_ERROR,
                error.code(),
                &error.to_string(),
                None,
            );
        }
    };
    let body = json!({
        "schema_version": 1,
        "status": "ok",
        "session_id": summary.session_id,
        "task_id": summary.task_id,
        "next_sequence": summary.next_sequence,
        "input_count": summary.input_count,
        "projection": projection.map(|state| json!({
            "revision": state.revision,
            "through_event_seq": state.through_event_seq,
            "plan_items": state.plan_items.len(),
            "checks": state.checks.len(),
            "changes": state.changes.len(),
        })),
        "events": events.iter().map(event_view).collect::<Vec<_>>(),
    });
    let _ = store.close().await;
    json_response(StatusCode::OK, &body)
}

/// A stream over a receiver, without adding a dependency for it.
///
/// `tokio-stream` is in the lockfile but not a direct dependency, and the whole
/// point of `ADR-N10` D1 is that this surface adds no dependency tree. Ten lines
/// of `Stream` is cheaper than a new direct edge.
struct ReceiverStream {
    receiver: mpsc::Receiver<Result<Frame<Bytes>, Infallible>>,
}

impl futures_util::Stream for ReceiverStream {
    type Item = Result<Frame<Bytes>, Infallible>;

    fn poll_next(
        mut self: std::pin::Pin<&mut Self>,
        context: &mut std::task::Context<'_>,
    ) -> std::task::Poll<Option<Self::Item>> {
        self.receiver.poll_recv(context)
    }
}

/// The safe view of one event: identity and correlation, never the payload.
///
/// A raw journal row can carry a transcript, a credential reference or an
/// internal decision; the web surface publishes what a view needs and nothing
/// else. `ADR-N10` D7.
fn event_view(event: &harness_types::EventEnvelope) -> Value {
    json!({
        "id": event.seq,
        "event_id": event.event_id,
        "event_type": event.event_type,
        "authority": event.authority,
        "correlation_id": event.correlation_id,
        "causation_id": event.causation_id,
        "continuity_critical": event.continuity_critical,
    })
}

/// Stream committed events from a cursor, with an explicit gap.
#[allow(clippy::too_many_lines)] // resolve, bound, stream: one ordering that must not be split
async fn session_events(state: &WebConfig, session: &str, query: &str) -> Response<Body> {
    let session_id = match SessionId::parse(session) {
        Ok(id) => id,
        Err(error) => {
            return error_response(StatusCode::BAD_REQUEST, error.code(), error.message(), None);
        }
    };
    let cursor_value = query
        .split('&')
        .find_map(|pair| pair.strip_prefix("cursor="));
    let cursor = match cursor_value {
        Some(value) => match value.parse::<u64>() {
            Ok(cursor) => cursor,
            Err(_) => {
                return error_response(
                    StatusCode::BAD_REQUEST,
                    ErrorCode::InvalidPayload,
                    "the event cursor must be a non-negative integer",
                    None,
                );
            }
        },
        None => 0,
    };
    let store = match open_store(state).await {
        Ok(store) => store,
        Err(error) => {
            return error_response(
                status_for(error.code()),
                error.code(),
                error.message(),
                None,
            );
        }
    };
    let summary = match store.session_summary(&session_id).await {
        Ok(Some(summary)) => summary,
        Ok(None) => {
            let _ = store.close().await;
            return error_response(
                StatusCode::NOT_FOUND,
                ErrorCode::TaskNotFound,
                "no such session",
                None,
            );
        }
        Err(error) => {
            let _ = store.close().await;
            return error_response(
                StatusCode::INTERNAL_SERVER_ERROR,
                error.code(),
                &error.to_string(),
                None,
            );
        }
    };
    // The retained range starts at the oldest sequence still in the journal. A
    // cursor below it means the client missed events that no longer exist, and
    // that is stated rather than papered over by replaying what is left.
    let oldest = match store.oldest_event_sequence(&session_id).await {
        Ok(oldest) => oldest.unwrap_or(summary.next_sequence),
        Err(error) => {
            let _ = store.close().await;
            return error_response(
                StatusCode::INTERNAL_SERVER_ERROR,
                error.code(),
                &error.to_string(),
                None,
            );
        }
    };
    let gap = cursor.saturating_add(1) < oldest;
    let effective_cursor = if gap {
        oldest.saturating_sub(1)
    } else {
        cursor
    };
    let initial_limit = if gap {
        LIVE_BUFFER_EVENTS.saturating_sub(1)
    } else {
        LIVE_BUFFER_EVENTS
    };
    let events = match store
        .load_events_after_limit(&session_id, effective_cursor, initial_limit)
        .await
    {
        Ok(events) => events,
        Err(error) => {
            let _ = store.close().await;
            return error_response(
                StatusCode::INTERNAL_SERVER_ERROR,
                error.code(),
                &error.to_string(),
                None,
            );
        }
    };
    let _ = store.close().await;

    let (sender, receiver) = mpsc::channel::<Result<Frame<Bytes>, Infallible>>(LIVE_BUFFER_EVENTS);
    let stream_state = state.clone();
    tokio::spawn(async move {
        if gap {
            let frame = format!(
                "event: gap\ndata: {{\"reason\":\"cursor_below_retained_range\",\"cursor\":{cursor},\"oldest_retained\":{oldest}}}\n\n"
            );
            if sender
                .try_send(Ok(Frame::data(Bytes::from(frame))))
                .is_err()
            {
                return;
            }
        }
        let mut last_sent = effective_cursor;
        for event in events {
            if sender
                .try_send(Ok(Frame::data(Bytes::from(journal_frame(&event)))))
                .is_err()
            {
                // A subscriber is cut at the buffer bound. EventSource resumes
                // from the last event id it received.
                return;
            }
            last_sent = event.seq;
        }
        let mut last_heartbeat = tokio::time::Instant::now();
        loop {
            tokio::time::sleep(Duration::from_millis(500)).await;
            let Ok(store) = open_store(&stream_state).await else {
                return;
            };
            let Ok(Some(summary)) = store.session_summary(&session_id).await else {
                let _ = store.close().await;
                return;
            };
            let latest = summary.next_sequence.saturating_sub(1);
            let Ok(oldest_event) = store.oldest_event_sequence(&session_id).await else {
                let _ = store.close().await;
                return;
            };
            let oldest = oldest_event.unwrap_or_else(|| latest.saturating_add(1));
            if last_sent.saturating_add(1) < oldest {
                let gap = format!(
                    "event: gap\ndata: {{\"reason\":\"cursor_below_retained_range\",\"cursor\":{last_sent},\"oldest_retained\":{oldest}}}\n\n"
                );
                let _ = store.close().await;
                let _ = sender.try_send(Ok(Frame::data(Bytes::from(gap))));
                return;
            }
            let Ok(events) = store
                .load_events_after_limit(&session_id, last_sent, LIVE_BUFFER_EVENTS)
                .await
            else {
                let _ = store.close().await;
                return;
            };
            let _ = store.close().await;
            for event in events {
                if event.seq <= last_sent {
                    continue;
                }
                if sender
                    .try_send(Ok(Frame::data(Bytes::from(journal_frame(&event)))))
                    .is_err()
                {
                    return;
                }
                last_sent = event.seq;
            }
            if last_heartbeat.elapsed() >= Duration::from_secs(15) {
                if sender
                    .try_send(Ok(Frame::data(Bytes::from_static(b": heartbeat\n\n"))))
                    .is_err()
                {
                    return;
                }
                last_heartbeat = tokio::time::Instant::now();
            }
        }
    });

    let stream = ReceiverStream { receiver };
    let body = StreamBody::new(stream).boxed();
    let mut response = Response::new(body);
    response.headers_mut().insert(
        header::CONTENT_TYPE,
        HeaderValue::from_static("text/event-stream"),
    );
    response
        .headers_mut()
        .insert(header::CACHE_CONTROL, HeaderValue::from_static("no-store"));
    response
        .headers_mut()
        .insert(header::CONNECTION, HeaderValue::from_static("keep-alive"));
    response
}

fn journal_frame(event: &harness_types::EventEnvelope) -> String {
    let data = serde_json::to_string(&event_view(event)).unwrap_or_else(|_| "{}".to_owned());
    format!("id: {}\nevent: journal\ndata: {data}\n\n", event.seq)
}

/// Admit one input through the session service, idempotently.
#[allow(clippy::too_many_lines)] // validation, auth and one service call belong in one place
async fn admit_input(
    state: &WebConfig,
    session: &str,
    body: &[u8],
    request_id: Option<&str>,
) -> Response<Body> {
    let session_id = match SessionId::parse(session) {
        Ok(id) => id,
        Err(error) => {
            return error_response(
                StatusCode::BAD_REQUEST,
                error.code(),
                error.message(),
                request_id,
            );
        }
    };
    let payload: Value = match serde_json::from_slice(body) {
        Ok(value) => value,
        Err(error) => {
            return error_response(
                StatusCode::BAD_REQUEST,
                ErrorCode::InvalidPayload,
                &format!("the request body is not JSON: {error}"),
                request_id,
            );
        }
    };
    let Some(text) = payload.get("text").and_then(Value::as_str) else {
        return error_response(
            StatusCode::BAD_REQUEST,
            ErrorCode::InvalidPayload,
            "an input requires a `text` field",
            request_id,
        );
    };
    if text.trim().is_empty() {
        return error_response(
            StatusCode::BAD_REQUEST,
            ErrorCode::InvalidPayload,
            "an input cannot be empty",
            request_id,
        );
    }
    let Some(request_id) = request_id else {
        return error_response(
            StatusCode::BAD_REQUEST,
            ErrorCode::InvalidPayload,
            "a mutation requires X-Ha-Request-Id so a retry is idempotent",
            None,
        );
    };
    // The request id becomes the durable input id, so the store's own
    // `(scope, input_id)` dedupe is what makes a retry safe. The API does not
    // implement a second dedupe: a second one could disagree with the first.
    let input_id = match InputId::parse(format!("input_{request_id}")) {
        Ok(id) => id,
        Err(error) => {
            return error_response(
                StatusCode::BAD_REQUEST,
                error.code(),
                "X-Ha-Request-Id must be a UUID",
                Some(request_id),
            );
        }
    };
    let store = match SqliteStore::open_writer(harness_store_sqlite::WriterOpenOptions::new(
        &state.data_dir,
        HostId::generate(),
    ))
    .await
    {
        Ok(store) => Arc::new(store),
        Err(error) => {
            return error_response(
                StatusCode::SERVICE_UNAVAILABLE,
                error.code(),
                &error.to_string(),
                Some(request_id),
            );
        }
    };
    let service = SessionService::new(Arc::clone(&store));
    let summary = match store.session_summary(&session_id).await {
        Ok(Some(summary)) => summary,
        Ok(None) => {
            let _ = Arc::try_unwrap(store);
            return error_response(
                StatusCode::NOT_FOUND,
                ErrorCode::TaskNotFound,
                "no such session",
                Some(request_id),
            );
        }
        Err(error) => {
            return error_response(
                StatusCode::INTERNAL_SERVER_ERROR,
                error.code(),
                &error.to_string(),
                Some(request_id),
            );
        }
    };
    let admitted = service
        .admit_input(AdmitInputRequest {
            session_id: session_id.clone(),
            task_id: summary.task_id.clone(),
            input_id,
            expected_sequence: summary.next_sequence,
            authority: SourceAuthority::User,
            raw_text: text.to_owned(),
            workspace: WorkspaceObservation {
                project_id: ProjectId::generate(),
                worktree_id: "web".to_owned(),
                base_commit: "0".repeat(40),
                observed_fingerprint: ContentHash::from_bytes(b"web"),
            },
            initial_plan_items: Vec::new(),
        })
        .await;
    // The writer is released before the response is returned. Leaving it to the
    // last `Arc` to drop makes the next request race this one for the writer
    // lock, which is how a second mutation intermittently came back empty.
    let closer = Arc::clone(&store);
    let response = match admitted {
        Ok(ack) => json_response(
            StatusCode::OK,
            &json!({
                "schema_version": 1,
                "status": "ok",
                "request_id": request_id,
                "session_id": session_id,
                "input_id": ack.input_id,
                "sequence": ack.sequence,
                "idempotent_replay": ack.idempotent_replay,
            }),
        ),
        Err(error) => error_response(
            status_for(error.code()),
            error.code(),
            &error.to_string(),
            Some(request_id),
        ),
    };
    drop(service);
    drop(store);
    if let Ok(store) = Arc::try_unwrap(closer) {
        let _ = store.close().await;
    }
    response
}
