use std::{
    env,
    error::Error,
    fmt::Write as _,
    fs,
    path::{Path, PathBuf},
};

use sha2::{Digest, Sha256};

fn main() -> Result<(), Box<dyn Error>> {
    let repository = PathBuf::from(env::var("CARGO_MANIFEST_DIR")?).join("../..");
    let skills = repository.join(".agents/skills");
    let notices = repository.join(".agents");
    let mut files = Vec::new();
    collect_files(&skills, &skills, &mut files)?;
    files.sort_by(|left, right| left.0.cmp(&right.0));
    if files.is_empty() {
        return Err("release build has no bundled skills".into());
    }

    let mut digest = Sha256::new();
    let mut source =
        String::from("// Generated by build.rs; skill bodies remain lazy until activation.\n");
    source.push_str("pub const BUNDLED_SKILL_FILES: &[(&str, &[u8])] = &[\n");
    for (relative, path) in &files {
        let bytes = fs::read(path)?;
        digest.update(relative.as_bytes());
        digest.update([0]);
        digest.update(&bytes);
        digest.update([0]);
        writeln!(
            source,
            "    ({relative:?}, include_bytes!({:?})),",
            path.display().to_string()
        )?;
    }
    source.push_str("];\n");
    let mut bundle_digest = String::with_capacity(64);
    for byte in digest.finalize() {
        write!(bundle_digest, "{byte:02x}")?;
    }
    writeln!(
        source,
        "pub const BUNDLED_SKILL_DIGEST: &str = {bundle_digest:?};"
    )?;
    source.push_str("pub const BUNDLED_NOTICES: &[(&str, &[u8])] = &[\n");
    for name in [
        "LICENSE-superpowers",
        "SUPERPOWERS-SOURCE.md",
        "LICENSE-deer-flow",
        "DEER-FLOW-SOURCE.md",
        "LICENSE-prime-agent",
        "PRIME-AGENT-SOURCE.md",
        "ANTHROPIC-SKILLS-SOURCE.md",
        "LICENSE-ui-ux-pro-max",
        "UI-UX-PRO-MAX-SOURCE.md",
    ] {
        let path = notices.join(name);
        println!("cargo:rerun-if-changed={}", path.display());
        writeln!(
            source,
            "    ({name:?}, include_bytes!({:?})),",
            path.display().to_string()
        )?;
    }
    source.push_str("];\n");
    fs::write(
        PathBuf::from(env::var("OUT_DIR")?).join("bundled_skills.rs"),
        source,
    )?;
    Ok(())
}

fn collect_files(
    root: &Path,
    directory: &Path,
    files: &mut Vec<(String, PathBuf)>,
) -> Result<(), Box<dyn Error>> {
    println!("cargo:rerun-if-changed={}", directory.display());
    for entry in fs::read_dir(directory)? {
        let entry = entry?;
        let path = entry.path();
        let kind = entry.file_type()?;
        if kind.is_dir() {
            collect_files(root, &path, files)?;
        } else if kind.is_file() {
            println!("cargo:rerun-if-changed={}", path.display());
            let relative = path.strip_prefix(root)?;
            let relative = relative
                .components()
                .map(|part| part.as_os_str().to_str().ok_or("skill path is not UTF-8"))
                .collect::<Result<Vec<_>, _>>()?
                .join("/");
            files.push((relative, path));
        } else {
            return Err(format!("unsupported bundled skill entry: {}", path.display()).into());
        }
    }
    Ok(())
}
