[package]
name = "harness-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "ha"
path = "src/main.rs"

[dependencies]
clap.workspace = true
harness-types = { path = "../harness-types" }
serde_json.workspace = true
toml.workspace = true

[lints]
workspace = true
